//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserFavorite
    {
        public string AspNetUsers_Id { get; set; }
        public int Item_idItem { get; set; }
        public System.DateTime dateOfCreation { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Item Item { get; set; }
    }
}
