//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Opinions = new HashSet<Opinion>();
            this.Sales = new HashSet<Sale>();
            this.Services = new HashSet<Service>();
        }

        public int idCustomer { get; set; }
        [Display(Name = "Imię:")]
        [Required(ErrorMessage = "Imię jest wymagane.")]
        public string name { get; set; }
        [Display(Name = "Nazwisko:")]
        [Required(ErrorMessage = "Nazwisko jest wymagane.")]
        public string surname { get; set; }
        [Display(Name = "Numer telefonu:")]
        [Required(ErrorMessage = "Numer telefonu jest wymagany.")]
        public Nullable<long> telephoneNumber { get; set; }
        [Display(Name = "Adres e-mail:")]
        [EmailAddress(ErrorMessage = "Podany adres e-mail jest nieprawidłowy.")]
        [Required(ErrorMessage = "Adres e-mail jest wymagany.")]
        public string emailAddress { get; set; }
        [Display(Name = "Adres zamieszkania:")]
        [Required(ErrorMessage = "Adres zamieszkania jest wymagany.")]
        public string addressOfResidence { get; set; }
        [Display(Name = "Kod pocztowy:")]
        [Required(ErrorMessage = "Kod pocztowy jest wymagany.")]
        public string zipCode { get; set; }
        public string AspNetUsers_idAspNetUsers { get; set; }
        [Display(Name = "Miejscowość:")]
        [Required(ErrorMessage = "Miejscowość jest wymagana.")]
        public int Locality_idLocality { get; set; }
        public Nullable<int> PermanentDiscount_idPermanentDiscount { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Locality Locality { get; set; }
        public virtual PermanentDiscount PermanentDiscount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
