//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Opinions = new HashSet<Opinion>();
            this.Sales = new HashSet<Sale>();
            this.Services = new HashSet<Service>();
        }
    
        public int idCustomer { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<long> telephoneNumber { get; set; }
        public string emailAddress { get; set; }
        public string addressOfResidence { get; set; }
        public string zipCode { get; set; }
        public string AspNetUsers_idAspNetUsers { get; set; }
        public int Locality_idLocality { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Locality Locality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
