//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureValueOfItem
    {
        public int Feature_idFeature1 { get; set; }
        public int Item_idItem1 { get; set; }
        public int FeatureValue_idFeatureValue { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual FeatureValue FeatureValue { get; set; }
        public virtual Item Item { get; set; }
    }
}
