//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klient()
        {
            this.Serwis = new HashSet<Serwis>();
            this.Sprzedaz = new HashSet<Sprzedaz>();
        }
    
        public int idKlient { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string login { get; set; }
        public string hash { get; set; }
        public Nullable<long> numerTelefonu { get; set; }
        public string adresEmail { get; set; }
        public string adresZamieszkania { get; set; }
        public string kodPocztowy { get; set; }
        public int Miejscowosc_idMiejscowosc { get; set; }
    
        public virtual Miejscowosc Miejscowosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serwis> Serwis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz> Sprzedaz { get; set; }
    }
}
