//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Note
    {
        public int idNote { get; set; }
        [Display(Name = "Notatka do zlecenia:")]
        [Required(ErrorMessage = "Notatka jest wymagana.")]
        public string note1 { get; set; }
    }
}
