//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int idService { get; set; }
        public string title { get; set; }
        public decimal price { get; set; }
        public System.DateTime dateOfEmployment { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateOfCompletion { get; set; }
        public int Customer_idCustomer { get; set; }
        public int ServiceType_idServiceType { get; set; }
        public int Employee_idEmployee { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
