//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serwis
    {
        public int idSerwis { get; set; }
        public string tytul { get; set; }
        public decimal cena { get; set; }
        public System.DateTime dataZlecenia { get; set; }
        public string opis { get; set; }
        public Nullable<System.DateTime> dataWykonania { get; set; }
        public int Klient_idKlient { get; set; }
        public int Pracownik_idPracownik { get; set; }
        public int TypSerwisu_idTypSerwisu { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual TypSerwisu TypSerwisu { get; set; }
    }
}
