//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprzedaz()
        {
            this.SzczegolySprzedazy = new HashSet<SzczegolySprzedazy>();
        }
    
        public int idSprzedaz { get; set; }
        public System.DateTime data { get; set; }
        public decimal wartosc { get; set; }
        public int Pracownik_idPracownik { get; set; }
        public int Klient_idKlient { get; set; }
        public int TypSprzedazy_idTypSprzedazy { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzczegolySprzedazy> SzczegolySprzedazy { get; set; }
        public virtual TypSprzedazy TypSprzedazy { get; set; }
    }
}
