//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bikevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SzczegolySprzedazy
    {
        public int Przedmiot_idPrzedmiot { get; set; }
        public int Sprzedaz_idSprzedaz { get; set; }
        public decimal wartosc { get; set; }
    
        public virtual Przedmiot Przedmiot { get; set; }
        public virtual Sprzedaz Sprzedaz { get; set; }
    }
}
